hw1
nonideas/java-course-2023 pull request #1
Opened 2023-10-09 13:47 UTC by nonideas

2023-10-11 17:35 UTC, infomouse requested changes

2023-10-11 17:35 UTC, infomouse commented on src/test/java/edu/hw1/CountDigitsTest.java
Имя класса тестов должно в формате ИмяКлассаTest, те Task2Test.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +        if (minutes > 35791394 || minutes == 35791394 && seconds > 7) {
Похоже на какую-то магию. Тут должны быть понятные константы. Но проще и эффективнее проверить длину строки.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +        int minutes = Integer.parseInt(minSec[0]);
Если в строке будет буква, то здесь получим NumberFormatException. А по условию должны возвращать -1.

Если знакомы с регулярками, то валидацию можно сделать с помощью метода String.matches().

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +    public static int minutesToSeconds(@NotNull String time) {
Надо понимать, что аннотация NotNull не дает защиты от передачи в метод null.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task3.java
> +    @SuppressWarnings("MagicNumber")
Не надо бездумно вещать аннотацию SuppressWarnings.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task5.java
> +    public static boolean isPalindromeDescendant(int number) {
isPalindromeDescendant(1) возвращает false, хотя это палиндром.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task6.java
> +        if (number == 6174) {
Число 6174 надо вынести в константу.

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task6.java
> +        StringBuilder reversed = new StringBuilder(new String(digits)).reverse();
Можно так же использовать Arrays.sort().

2023-10-11 17:35 UTC, infomouse commented on src/main/java/edu/hw1/Task8.java
> +        int[][] moves = {{-2, -1}, {-2, 1}, {-1, -2}, {-1, 2}, {1, -2}, {1, 2}, {2, -1}, {2, 1}};
На каждый вызов функции создается массив, который не изменяется. Надо вынести в константу.

2023-10-12 16:26 UTC, nonideas commented on src/main/java/edu/hw1/Task6.java
> +        StringBuilder reversed = new StringBuilder(new String(digits)).reverse();
Немного не понимаю зачем второй раз использовать Arrays.sort(), если можно применить reverse к уже отсортированной строке.

2023-10-12 16:46 UTC, infomouse commented on src/main/java/edu/hw1/Task6.java
> +        StringBuilder reversed = new StringBuilder(new String(digits)).reverse();
1. Выделение памяти (оператор new) не дешевая операция. Сортировка в готовом массиве будет быстрее с учетом этого.
2. Мы создали два "мусорных" объекта (String и StringBuilder). GC конечно работает быстро, но это не повод бездумно плодить мусор.
Все это конечно в контексте этой задачи мелочи, но в высоконагруженных системах играет важную роль.

2023-10-14 09:30 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +    @SuppressWarnings("MagicNumber")
Можно убрать, если сделать константу SECONDS_IN_MINUTE. Ее же можно использовать вместо MAX_SECONDS.

2023-10-14 09:36 UTC, infomouse requested changes

2023-10-14 09:36 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +    @SuppressWarnings("MagicNumber")
Можно убрать, если сделать константу SECONDS_IN_MINUTE. Ее же можно использовать вместо MAX_SECONDS.

2023-10-14 09:36 UTC, infomouse commented on src/main/java/edu/hw1/Task1.java
> +        LOGGER.info(minutesToSeconds("01:00"));
Отладочного кода не должно быть. Все проверки должны быть в тестах.

2023-10-14 09:36 UTC, infomouse commented on src/main/java/edu/hw1/Task4.java
> +    @SuppressWarnings("MagicNumber")
Надо убрать.

2023-10-14 09:36 UTC, infomouse commented on src/main/java/edu/hw1/Task7.java
> +    @SuppressWarnings("MagicNumber")
Надо убрать.

2023-10-14 09:36 UTC, infomouse commented on src/main/java/edu/hw1/Task8.java
> +    @SuppressWarnings("MagicNumber")
Надо убрать.

2023-10-17 12:41 UTC, merged