project1
nonideas/java-course-2023 pull request #3
Opened 2023-10-19 11:01 UTC by nonideas

2023-10-20 20:17 UTC, infomouse requested changes

2023-10-20 20:17 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +                LOGGER.info("You lost!");
Это должно быть частью message в GuessResult.Defeat.

2023-10-20 20:17 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +            if (result instanceof GuessResult.Defeat) {
Плохая практика. Такой код сложно расширять. Если в игре появится другие терминирующие состояния, то вы будете постоянно расширять этот if. Более гибкое решение - это добавить флаг gameOver в GuessResult.

2023-10-21 07:28 UTC, nonideas commented on src/main/java/edu/project1/ConsoleHangman.java
> +                LOGGER.info("You lost!");
В примере задания у нас идет следующий порядок вывода сообщений:
> Guess a letter:
< o
> Missed, mistake 5 out of 5.
>
> The word: **n*n*
>
> You lost!
сообщение You lost! идет в самом конце, а если поместить его в message, то оно будет сразу после Missed, mistake 5 out of 5. Поэтому я добавил String gameOver(); в GuessResult, чтобы его можно было вывести в самом конце.

2023-10-21 08:43 UTC, infomouse commented on src/main/java/edu/project1/ConsoleHangman.java
> +                LOGGER.info("You lost!");
Пример - это не требование. Подгонять решение под него не надо.
По-хорошему логика должна быть изолирована от способа вывода, а у вас логика подстроена под вывод. Но этому научимся по ходу курса.

2023-10-22 16:39 UTC, merged